const usdRates={USD:1,CHF:.80,EUR:.855,GBP:.74,CAD:1.38,AUD:1.52,JPY:147,CNY:7.12,HKD:7.80,SGD:1.28,KRW:1390,INR:88.2,MXN:18.7,BRL:5.42,TRY:41.2,PLN:3.64,SEK:9.45,NOK:10.05,DKK:6.38,AED:3.6725,SAR:3.75,NZD:1.69,THB:31.9,MYR:4.22,ZAR:17.7,CLP:963,COP:4010,CZK:20.9,HUF:337,RON:4.34,ILS:3.35,TWD:31.4,PHP:57.2,VND:26350};
let catalog={},liveRows=[],selectedMapCountry=null;
const $=s=>document.querySelector(s),productSelect=$('#productSelect'),categorySelect=$('#categorySelect'),currencySelect=$('#currencySelect'),regionSelect=$('#regionSelect'),viewSelect=$('#viewSelect'),table=$('#priceTable'),stats=$('#stats');
const money=(v,c)=>new Intl.NumberFormat('fr-CH',{style:'currency',currency:c,maximumFractionDigits:0}).format(v);
function convert(r,target){const from=usdRates[r.currency],to=usdRates[target];return from&&to?r.price/from*to:r.price}
function buildCategories(){const cats=[...new Set(Object.values(catalog).map(p=>p.category))];categorySelect.innerHTML='<option value="all">Toutes les catégories</option>'+cats.map(c=>`<option value="${c}">${c}</option>`).join('');buildProducts()}
function buildProducts(){const cat=categorySelect.value;const entries=Object.entries(catalog).filter(([,p])=>cat==='all'||p.category===cat);productSelect.innerHTML=entries.map(([name,p])=>`<option value="${name}">${name}</option>`).join('');sync()}
function renderCatalogue(){const groups={};Object.entries(catalog).forEach(([name,p])=>(groups[p.category]??=[]).push(name));$('#catalogueGrid').innerHTML=Object.entries(groups).map(([cat,names])=>`<article><b>${String(names.length).padStart(2,'0')}</b><h3>${cat}</h3><p>${names.join(' · ')}</p></article>`).join('')}
function render(){const target=currencySelect.value,region=regionSelect.value;$('#convertedHeader').textContent=`Prix en ${target}`;let rows=liveRows.filter(r=>region==='all'||r.region===region).map(r=>({...r,converted:convert(r,target)})).sort((a,b)=>a.converted-b.converted);if(viewSelect.value==='top10')rows=rows.slice(0,10);if(!rows.length){table.innerHTML='<tr><td colspan="6" class="empty">Aucune donnée de prix disponible pour cette sélection.</td></tr>';stats.innerHTML='';renderMap();return}const min=rows[0].converted,max=Math.max(...rows.map(r=>r.converted)),spread=(max-min)/min*100;stats.innerHTML=`<div class="stat"><small>MEILLEUR PRIX</small><strong>${money(min,target)}</strong></div><div class="stat"><small>MARCHÉ #1</small><strong>${rows[0].flag||'🌐'} ${rows[0].country}</strong></div><div class="stat"><small>ÉCART MAX.</small><strong class="positive">+${spread.toFixed(1)}%</strong></div>`;table.innerHTML=rows.map((r,i)=>{const pct=(r.converted-min)/min*100;return `<tr><td class="rank">${String(i+1).padStart(2,'0')}</td><td><div class="country"><span class="flag">${r.flag||'🌐'}</span><span>${r.country}<small>${r.region}</small></span></div></td><td>${money(r.price,r.currency)}</td><td class="converted">${money(r.converted,target)}</td><td>${i===0?'<span class="best">BEST PRICE</span>':`<span class="delta ${pct>15?'high':''}">+${pct.toFixed(1)}%</span>`}</td><td><a class="shop-link" target="_blank" rel="noopener" href="${r.url}">Apple Store ↗</a></td></tr>`}).join('');renderMap()}
async function renderMap(){const el=$('#worldMap');if(!el)return;const target=currencySelect.value||'CHF';$('#mapProduct').textContent=productSelect.value||'Produit';$('#mapCurrency').textContent=target;if(!liveRows.length){el.innerHTML='<div class="map-loading">Aucune donnée de prix disponible</div>';return}try{const[d3mod,topomod,worldmod]=await Promise.all([import('https://cdn.jsdelivr.net/npm/d3@7.9.0/+esm'),import('https://cdn.jsdelivr.net/npm/topojson-client@3.1.0/+esm'),import('https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-50m.json/+esm')]);const d3=d3mod.default||d3mod,topojson=topomod.default||topomod,world=worldmod.default||worldmod,countries=topojson.feature(world,world.objects.countries).features,byIso=new Map(liveRows.filter(r=>r.isoNumeric).map(r=>[String(r.isoNumeric).padStart(3,'0'),r])),values=liveRows.map(r=>convert(r,target)).filter(Number.isFinite).sort((a,b)=>a-b);const min=values[0],max=values[values.length-1],color=d3.scaleSequential().domain([max,min]).interpolator(d3.interpolateRgbBasis(['#071a38','#123d77','#286ac2','#67a8ff'])),svg=d3.select(el).selectAll('svg').data([null]).join('svg').attr('viewBox','0 0 960 520').attr('role','img').attr('aria-label','Prix Apple par pays');svg.selectAll('*').remove();const projection=d3.geoNaturalEarth1().fitExtent([[10,10],[950,510]],{type:'FeatureCollection',features:countries}),path=d3.geoPath(projection);svg.selectAll('path').data(countries).join('path').attr('d',path).attr('class',d=>byIso.has(String(d.id).padStart(3,'0'))?'market':'no-data').attr('fill',d=>{const r=byIso.get(String(d.id).padStart(3,'0'));return r?color(convert(r,target)):'#101720'}).on('click',(event,d)=>{const r=byIso.get(String(d.id).padStart(3,'0'));if(r)selectMapCountry(r,target,event.currentTarget)});if(selectedMapCountry){const r=byIso.get(String(selectedMapCountry.isoNumeric).padStart(3,'0'));if(r)showMapDetail(r,target)}}catch(e){el.innerHTML='<div class="map-loading">Carte indisponible — les prix restent accessibles dans le tableau.</div>'}}
function selectMapCountry(r,target,node){selectedMapCountry=r;document.querySelectorAll('#worldMap path.selected').forEach(x=>x.classList.remove('selected'));node.classList.add('selected');showMapDetail(r,target)}
function showMapDetail(r,target){const converted=convert(r,target),rank=[...liveRows].map(x=>convert(x,target)).sort((a,b)=>a-b).indexOf(converted)+1;$('#mapDetail').innerHTML=`<div><small>${r.flag||'🌐'} ${r.region||''}</small><strong>${r.country}</strong><span class="map-price">${money(converted,target)}</span><span class="map-rank">#${rank} mondial</span></div>`}
async function sync(){const product=productSelect.value;try{const data=await fetch('data/prices.json?'+Date.now()).then(r=>r.json());liveRows=data.products?.[product]?.rows||[];render();$('#lastUpdated').textContent=data.updatedAt?`Dernière synchronisation : ${new Date(data.updatedAt).toLocaleString('fr-CH')}`:'Aucune donnée'}catch{liveRows=[];render()}}
async function load(){try{const data=await fetch('data/prices.json?'+Date.now()).then(r=>r.json());catalog=data.products||{};$('#marketCount').textContent=data.marketCount||'—';$('#productCount').textContent=data.productCount||Object.keys(catalog).length||'—';buildCategories();renderCatalogue();$('#syncStatus').textContent=`${data.marketCount||0} marchés · ${Object.keys(catalog).length} produits`}catch{$('#syncStatus').textContent='Données indisponibles';$('#marketCount').textContent='—';liveRows=[];render()}}
categorySelect.addEventListener('change',buildProducts);productSelect.addEventListener('change',sync);currencySelect.addEventListener('change',render);regionSelect.addEventListener('change',render);viewSelect.addEventListener('change',render);$('#refresh').addEventListener('click',sync);load();